{{-- resources/views/Procurement/Project-Purchase/create.blade.php --}}
@extends('layouts.app')

@section('title', 'Create Purchase Order')

@section('content')
<div class="container-fluid py-4">
    <div class="row justify-content-center">
        <div class="col-12 col-xl-10">
            <!-- Header -->
            <div class="d-flex justify-content-between align-items-center mb-4">
                <div>
                    <h4 class="mb-0">Create New Purchase Order</h4>
                    <p class="text-muted mb-0">Fill in the details below to create a new purchase order</p>
                </div>
                <a href="{{ route('procurement.project-purchases.index') }}" 
                   class="btn btn-outline-secondary rounded-3 px-4">
                    <i class="fas fa-arrow-left me-2"></i>Back
                </a>
            </div>

            <div class="card border-0 shadow-sm rounded-4">
                <div class="card-body p-4">
                    @if(session('error'))
                        <div class="alert alert-danger alert-dismissible fade show mb-4" role="alert">
                            <i class="fas fa-exclamation-circle me-2"></i>
                            {{ session('error') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                        </div>
                    @endif

                    <form action="{{ route('procurement.project-purchases.store') }}" method="POST" id="purchaseForm">
                        @csrf
                        
                        <!-- PO Information Card -->
                        <div class="card border-0 bg-light mb-4">
                            <div class="card-body">
                                <h6 class="mb-3 text-primary fw-semibold">
                                    <i class="fas fa-file-invoice me-2"></i>PO Information
                                </h6>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">PO Number</label>
                                            <div class="input-group">
                                                <input type="text" class="form-control bg-white fw-bold" 
                                                       value="{{ $autoGeneratedPO }}" readonly>
                                                <span class="input-group-text bg-success text-white">
                                                    <i class="fas fa-hashtag"></i>
                                                </span>
                                            </div>
                                            <small class="form-text text-muted mt-1">Auto-generated PO number</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">Date <span class="text-danger">*</span></label>
                                            <input type="date" class="form-control" name="date" 
                                                   value="{{ date('Y-m-d') }}" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="alert alert-info alert-dismissible fade show mt-2" role="alert">
                                    <i class="fas fa-info-circle me-2"></i>
                                    Status will be automatically set to <strong>Pending</strong> and must be approved by Finance department.
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                                </div>
                            </div>
                        </div>

                        <!-- Material & Quantity Card -->
                        <div class="card border-0 bg-light mb-4">
                            <div class="card-body">
                                <h6 class="mb-3 text-primary fw-semibold">
                                    <i class="fas fa-boxes me-2"></i>Material Details
                                </h6>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">Material <span class="text-danger">*</span></label>
                                            <select class="form-select select2-material" name="material_id" id="materialSelect" required>
                                                <option value="">Select Material</option>
                                                @foreach($materials as $material)
                                                    <option value="{{ $material->id }}" 
                                                            data-price="{{ $material->price ?? 0 }}">
                                                        {{ $material->name }} 
                                                        @if($material->price)
                                                            (${{ number_format($material->price, 2) }})
                                                        @endif
                                                    </option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">Quantity <span class="text-danger">*</span></label>
                                            <div class="input-group">
                                                <input type="number" class="form-control" name="quantity" id="quantity" 
                                                       min="1" step="1" value="1" required>
                                                <span class="input-group-text">pcs</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">Unit Price ($) <span class="text-danger">*</span></label>
                                            <div class="input-group">
                                                <span class="input-group-text">$</span>
                                                <input type="number" class="form-control" name="unit_price" id="unitPrice" 
                                                       step="0.01" min="0" placeholder="0.00" required>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Project & Department Card -->
                        <div class="card border-0 bg-light mb-4">
                            <div class="card-body">
                                <h6 class="mb-3 text-primary fw-semibold">
                                    <i class="fas fa-project-diagram me-2"></i>Project & Department
                                </h6>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">Department <span class="text-danger">*</span></label>
                                            <select class="form-select select2-department" name="department_id" required>
                                                <option value="">Select Department</option>
                                                @foreach($departments as $department)
                                                    <option value="{{ $department->id }}">{{ $department->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">Project <span class="text-danger">*</span></label>
                                            <select class="form-select select2-project" name="project_id" required>
                                                <option value="">Select Project</option>
                                                @foreach($projects as $project)
                                                    <option value="{{ $project->id }}">{{ $project->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">Job Order</label>
                                            <select class="form-select select2-joborder" name="job_order_id">
                                                <option value="">Select Job Order</option>
                                                @foreach($jobOrders as $jobOrder)
                                                    <option value="{{ $jobOrder->id }}">{{ $jobOrder->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Supplier & PIC Card -->
                        <div class="card border-0 bg-light mb-4">
                            <div class="card-body">
                                <h6 class="mb-3 text-primary fw-semibold">
                                    <i class="fas fa-truck me-2"></i>Supplier & Contact Person
                                </h6>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">Supplier <span class="text-danger">*</span></label>
                                            <select class="form-select select2-supplier" name="supplier_id" required>
                                                <option value="">Select Supplier</option>
                                                @foreach($suppliers as $supplier)
                                                    <option value="{{ $supplier->id }}">{{ $supplier->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">Person In Charge (PIC) <span class="text-danger">*</span></label>
                                            <select class="form-select select2-pic" name="pic_id" required>
                                                <option value="">Select PIC</option>
                                                @foreach($employees as $employee)
                                                    <option value="{{ $employee->id }}">{{ $employee->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Financial Details Card -->
                        <div class="card border-0 bg-light mb-4">
                            <div class="card-body">
                                <h6 class="mb-3 text-primary fw-semibold">
                                    <i class="fas fa-calculator me-2"></i>Financial Details
                                </h6>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="card bg-white border mb-3">
                                            <div class="card-body text-center">
                                                <label class="form-label fw-medium text-muted mb-2">Total Price</label>
                                                <h3 class="text-primary" id="displayTotalPrice">$0.00</h3>
                                                <input type="hidden" name="total_price" id="totalPrice" value="0">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="mb-3">
                                            <label class="form-label fw-medium">Freight Cost</label>
                                            <div class="input-group">
                                                <span class="input-group-text">$</span>
                                                <input type="number" class="form-control" name="freight" id="freight" 
                                                       step="0.01" min="0" value="0" placeholder="0.00">
                                            </div>
                                            <small class="form-text text-muted">Optional - Add if there are shipping costs</small>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="card bg-success border-0 mb-3">
                                            <div class="card-body text-center text-white">
                                                <label class="form-label fw-medium mb-2">Invoice Total</label>
                                                <h3 id="displayInvoiceTotal">$0.00</h3>
                                                <input type="hidden" name="invoice_total" id="invoiceTotal" value="0">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Notes Card -->
                        <div class="card border-0 bg-light mb-4">
                            <div class="card-body">
                                <h6 class="mb-3 text-primary fw-semibold">
                                    <i class="fas fa-sticky-note me-2"></i>Additional Information
                                </h6>
                                <div class="mb-3">
                                    <label class="form-label fw-medium">Notes</label>
                                    <textarea class="form-control" name="note" rows="3" 
                                              placeholder="Optional notes, special instructions, or additional information..."></textarea>
                                    <small class="form-text text-muted">Add any relevant notes or instructions for this purchase order</small>
                                </div>
                            </div>
                        </div>

                        <!-- Important Notes -->
                        <div class="alert alert-warning alert-dismissible fade show mb-4" role="alert">
                            <div class="d-flex">
                                <i class="fas fa-exclamation-triangle me-3 fs-4"></i>
                                <div>
                                    <h6 class="alert-heading mb-2">Important Information</h6>
                                    <ul class="mb-0 ps-3">
                                        <li>All purchase orders will be created with <strong>Pending</strong> status</li>
                                        <li>Tracking number will be added by Finance department after approval</li>
                                        <li>Purchase orders can only be edited or deleted while in Pending status</li>
                                        <li>Once approved, tracking number will be visible and status cannot be changed</li>
                                    </ul>
                                </div>
                            </div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                        </div>

                        <!-- Form Actions -->
                        <div class="d-flex justify-content-between align-items-center pt-4 border-top">
                            <div>
                                <a href="{{ route('procurement.project-purchases.index') }}" 
                                   class="btn btn-outline-secondary px-4">
                                    <i class="fas fa-times me-2"></i>Cancel
                                </a>
                            </div>
                            <div>
                                <button type="button" class="btn btn-outline-info px-4 me-2" onclick="calculateTotals()">
                                    <i class="fas fa-calculator me-2"></i>Calculate
                                </button>
                                <button type="submit" class="btn btn-primary px-4">
                                    <i class="fas fa-paper-plane me-2"></i>Create Purchase Order
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .card {
        transition: all 0.2s;
    }
    
    .card:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 12px rgba(0,0,0,0.08);
    }
    
    .select2-material, 
    .select2-department,
    .select2-project,
    .select2-joborder,
    .select2-supplier,
    .select2-pic {
        width: 100% !important;
    }
    
    .form-label {
        font-size: 0.9rem;
        color: #4a5568;
    }
    
    .alert {
        border: none;
        border-left: 4px solid;
    }
    
    .alert-info {
        border-left-color: #4299e1;
        background-color: #ebf8ff;
    }
    
    .alert-warning {
        border-left-color: #ed8936;
        background-color: #fffaf0;
    }
    
    .input-group-text {
        background-color: #f7fafc;
        border-color: #e2e8f0;
    }
    
    .form-control:focus, .form-select:focus {
        border-color: #4299e1;
        box-shadow: 0 0 0 0.2rem rgba(66, 153, 225, 0.25);
    }
</style>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Initialize Select2 for all dropdowns
    $('.select2-material, .select2-department, .select2-project, .select2-joborder, .select2-supplier, .select2-pic').select2({
        placeholder: "Select an option",
        allowClear: true,
        width: '100%'
    });

    const materialSelect = document.getElementById('materialSelect');
    const quantityInput = document.getElementById('quantity');
    const unitPriceInput = document.getElementById('unitPrice');
    const freightInput = document.getElementById('freight');
    const totalPriceInput = document.getElementById('totalPrice');
    const invoiceTotalInput = document.getElementById('invoiceTotal');
    const displayTotalPrice = document.getElementById('displayTotalPrice');
    const displayInvoiceTotal = document.getElementById('displayInvoiceTotal');

    // Function to format currency
    function formatCurrency(amount) {
        return '$' + parseFloat(amount).toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,');
    }

    // Function to calculate totals
    window.calculateTotals = function() {
        const quantity = parseFloat(quantityInput.value) || 0;
        const unitPrice = parseFloat(unitPriceInput.value) || 0;
        const freight = parseFloat(freightInput.value) || 0;
        
        const totalPrice = quantity * unitPrice;
        const invoiceTotal = totalPrice + freight;
        
        // Update hidden inputs
        totalPriceInput.value = totalPrice.toFixed(2);
        invoiceTotalInput.value = invoiceTotal.toFixed(2);
        
        // Update display
        displayTotalPrice.textContent = formatCurrency(totalPrice);
        displayInvoiceTotal.textContent = formatCurrency(invoiceTotal);
        
        // Visual feedback
        if (totalPrice > 0) {
            displayTotalPrice.classList.remove('text-primary');
            displayTotalPrice.classList.add('text-success');
        }
        
        if (invoiceTotal > 0) {
            displayInvoiceTotal.style.transform = 'scale(1.05)';
            setTimeout(() => {
                displayInvoiceTotal.style.transform = 'scale(1)';
            }, 300);
        }
    };

    // Auto-fill unit price when material is selected
    $(materialSelect).on('change', function() {
        const selectedOption = this.options[this.selectedIndex];
        const materialPrice = selectedOption.getAttribute('data-price');
        
        if (materialPrice && materialPrice > 0) {
            unitPriceInput.value = materialPrice;
            calculateTotals();
        }
    });

    // Calculate totals on input change
    [quantityInput, unitPriceInput, freightInput].forEach(input => {
        input.addEventListener('input', calculateTotals);
        input.addEventListener('change', calculateTotals);
    });

    // Form validation
    document.getElementById('purchaseForm').addEventListener('submit', function(e) {
        const unitPrice = parseFloat(unitPriceInput.value);
        const quantity = parseFloat(quantityInput.value);
        
        // Check if all required fields are filled
        const requiredFields = this.querySelectorAll('[required]');
        let isValid = true;
        let firstInvalidField = null;
        
        requiredFields.forEach(field => {
            if (!field.value.trim()) {
                isValid = false;
                if (!firstInvalidField) {
                    firstInvalidField = field;
                }
                field.classList.add('is-invalid');
            } else {
                field.classList.remove('is-invalid');
            }
        });
        
        if (!isValid) {
            e.preventDefault();
            alert('Please fill in all required fields marked with *');
            if (firstInvalidField) {
                firstInvalidField.focus();
            }
            return;
        }
        
        if (unitPrice <= 0) {
            e.preventDefault();
            alert('Unit price must be greater than 0');
            unitPriceInput.focus();
            unitPriceInput.classList.add('is-invalid');
            return;
        } else {
            unitPriceInput.classList.remove('is-invalid');
        }
        
        if (quantity <= 0) {
            e.preventDefault();
            alert('Quantity must be greater than 0');
            quantityInput.focus();
            quantityInput.classList.add('is-invalid');
            return;
        } else {
            quantityInput.classList.remove('is-invalid');
        }
        
        // Show loading state
        const submitBtn = this.querySelector('button[type="submit"]');
        const originalText = submitBtn.innerHTML;
        submitBtn.innerHTML = '<i class="fas fa-spinner fa-spin me-2"></i>Creating...';
        submitBtn.disabled = true;
        
        // Re-enable after 3 seconds if form submission fails
        setTimeout(() => {
            submitBtn.innerHTML = originalText;
            submitBtn.disabled = false;
        }, 3000);
    });

    // Initialize calculations on page load
    calculateTotals();
    
    // Set today's date as default
    const dateInput = document.querySelector('input[name="date"]');
    if (dateInput && !dateInput.value) {
        dateInput.value = new Date().toISOString().split('T')[0];
    }
    
    // Auto-calculate every 2 seconds while user is typing
    let calculateTimeout;
    [quantityInput, unitPriceInput, freightInput].forEach(input => {
        input.addEventListener('input', function() {
            clearTimeout(calculateTimeout);
            calculateTimeout = setTimeout(calculateTotals, 500);
        });
    });
});
</script>
@endsection